### ISSUE TITLE
How to get SP metadata

### ISSUE THREAD

**Issue by devabe** [OhadR/spring-oAuth2-SAML-integration#2]
Hello,
  I am integrating your code and when I start tomcat and try to get the bridge SP metadata in order to register it against and Identity Provider, I don't knwo how to do it.

   Please explain where the get the bridge SP metadata for SAML Idp.

Thanks.

**Comment by OhadR** [comment]
hi

what is your SP that you work with? have a look here: 

https://docs.spring.io/autorepo/docs/spring-security-saml/1.0.x/reference/html/configuration-metadata.html#configuration-metadata-sp

> Service provider metadata contains keys, services and URLs defining SAML endpoints of your application. Metadata can be either generated automatically upon first request to the service, or it can be pre-created (see Chapter 11, Sample application). Once created metadata needs to be provided to the identity providers with whom we want to establish trust.


my code has several sample idp-xml files, but in order to make it work on your side with your real SP, you should use the real SP-metadata, which you should get from your SP.

**Comment by devabe** [comment]
Thank you for the hint.
Have you please a Oauth2 client example code for this bridge Oauth2-Saml server ?
And how to configure and create clients credentials and grants inside the Oauth part of the server ?

**Comment by OhadR** [comment]
I have this repository: https://github.com/OhadR/oAuth2-sample which is a complete running example of oAuth2.0 flow, including all 3 components: client, resource-server and auth-server.

**Comment by devabe** [comment]
Good, thank you.
